version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\mg
environment:
  MSYS2_DIR: msys64
  ACCESS_KEY:
    secure: 4U3SfYBNNlc0VXB/9kPvqFH0qbzOD3FXHIY7SuRFvcQ=
  SECRET_KEY:
    secure: PtL0a/tSy8HJbUiwu8GNvx+UfOeOiSTrqGxmGswskxs8EBVLIJX5k2LgnX85V45G

  matrix:
    - MSYSTEM: MINGW64
      myarch: x86_64

build_script:
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    bash -c "pacman -Syu --noconfirm"
    
    bash -c "pacman -Syu --noconfirm"

    bash -c "pacman -S --needed --noconfirm mingw-w64-$myarch-nasm mingw-w64-$myarch-hidapi mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-SDL2_net mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 mingw-w64-$myarch-python3-pip mingw-w64-$myarch-python3-pyopenssl zip"

    cd %APPVEYOR_BUILD_FOLDER%

    bash -c "python3 -m pip install awscli"

    bash -c "export HOST_CPU=$myarch; export AWS_ACCESS_KEY_ID=$ACCESS_KEY; export AWS_SECRET_ACCESS_KEY=$SECRET_KEY; if [ -z "$APPVEYOR_PULL_REQUEST_NUMBER" ]; then ./build.sh aws; fi"
